import type {Value} from "@/types";


export const ValuesList: Value[] = [
    { "id": 1, "name": "ACCEPTANCE", "description": "to be accepted as I am" },
    { "id": 2, "name": "ACCURACY", "description": "to be correct in my opinions and beliefs" },
    { "id": 3, "name": "ACHIEVEMENT", "description": "to have important accomplishments" },
    { "id": 4, "name": "ADVENTURE", "description": "to have new and exciting experiences" },
    { "id": 5, "name": "ART", "description": "to appreciate or express myself in art" },
    { "id": 6, "name": "ATTRACTIVENESS", "description": "to be physically attractive" },
    { "id": 7, "name": "AUTHORITY", "description": "to be in charge of others" },
    { "id": 8, "name": "AUTONOMY", "description": "to be self-determined and independent" },
    { "id": 9, "name": "BEAUTY", "description": "to appreciate beauty around me" },
    { "id": 10, "name": "BELONGING", "description": "to have a sense of belonging, being part of" },
    { "id": 11, "name": "CARING", "description": "to take care of others" },
    { "id": 12, "name": "CHALLENGE", "description": "to take on difficult tasks and problems" },
    { "id": 13, "name": "COMFORT", "description": "to have a pleasant and comfortable life" },
    { "id": 14, "name": "COMMITMENT", "description": "to make enduring, meaningful commitments" },
    { "id": 15, "name": "COMPASSION", "description": "to feel and act on concern for others" },
    { "id": 16, "name": "COMPLEXITY", "description": "to embrace the intricacies of life" },
    { "id": 17, "name": "COMPROMISE", "description": "to be willing to give and take in reaching agreements" },
    { "id": 18, "name": "CONTRIBUTION", "description": "to make a lasting contribution in the world" },
    { "id": 19, "name": "COOPERATION", "description": "to work collaboratively with others" },
    { "id": 20, "name": "COURAGE", "description": "to be brave and strong in the face of adversity" },
    { "id": 21, "name": "COURTESY", "description": "to be considerate and polite toward others" },
    { "id": 22, "name": "CREATIVITY", "description": "to create new things or ideas" },
    { "id": 23, "name": "CURIOSITY", "description": "to seek out, experience, and learn new things" },
    { "id": 24, "name": "DEPENDABILITY", "description": "to be reliable and trustworthy" },
    { "id": 25, "name": "DILIGENCE", "description": "to be thorough and conscientious in whatever I do" },
    { "id": 26, "name": "DUTY", "description": "to carry out my duties and obligations" },
    { "id": 27, "name": "ECOLOGY", "description": "to live in harmony with the environment" },
    { "id": 28, "name": "EXCITEMENT", "description": "to have a life full of thrills and stimulation" },
    { "id": 29, "name": "FAITHFULNESS", "description": "to be loyal and true in relationships" },
    { "id": 30, "name": "FAME", "description": "to be known and recognized" },
    { "id": 31, "name": "FAMILY", "description": "to have a happy, loving family" },
    { "id": 32, "name": "FITNESS", "description": "to be physically fit and strong" },
    { "id": 33, "name": "FLEXIBILITY", "description": "to adjust to new circumstances easily" },
    { "id": 34, "name": "FORGIVENESS", "description": "to be forgiving of others" },
    { "id": 35, "name": "FREEDOM", "description": "to be free from undue restrictions and limitations" },
    { "id": 36, "name": "FRIENDSHIP", "description": "to have close, supportive friends" },
    { "id": 37, "name": "FUN", "description": "to play and have fun" },
    { "id": 38, "name": "GENEROSITY", "description": "to give what I have to others" },
    { "id": 39, "name": "GENUINENESS", "description": "to act in a manner that is true to who I am" },
    { "id": 40, "name": "GOD’S WILL", "description": "to seek and obey the will of God" },
    { "id": 41, "name": "GRATITUDE", "description": "to be thankful and appreciative" },
    { "id": 42, "name": "GROWTH", "description": "to keep changing and growing" },
    { "id": 43, "name": "HEALTH", "description": "to be physically well and healthy" },
    { "id": 44, "name": "HONESTY", "description": "to be honest and truthful" },
    { "id": 45, "name": "HOPE", "description": "to maintain a positive and optimistic outlook" },
    { "id": 46, "name": "HUMILITY", "description": "to be modest and unassuming" },
    { "id": 47, "name": "HUMOR", "description": "to see the humorous side of myself and the world" },
    { "id": 48, "name": "IMAGINATION", "description": "to have dreams and see possibilities" },
    { "id": 49, "name": "INDEPENDENCE", "description": "to be free from depending on others" },
    { "id": 50, "name": "INDUSTRY", "description": "to work hard and well at my life tasks" },
    { "id": 51, "name": "INNER PEACE", "description": "to experience personal peace" },
    { "id": 52, "name": "INTEGRITY", "description": "to live my daily life in a way that is consistent with my values" },
    { "id": 53, "name": "INTELLIGENCE", "description": "to keep my mind sharp and active" },
    { "id": 54, "name": "INTIMACY", "description": "to share my innermost experiences with others" },
    { "id": 55, "name": "JUSTICE", "description": "to promote fair and equal treatment for all" },
    { "id": 56, "name": "KNOWLEDGE", "description": "to learn and contribute valuable knowledge" },
    { "id": 57, "name": "LEADERSHIP", "description": "to inspire and guide others" },
    { "id": 58, "name": "LEISURE", "description": "to take time to relax and enjoy" },
    { "id": 59, "name": "LOVED", "description": "to be loved by those close to me" },
    { "id": 60, "name": "LOVING", "description": "to give love to others" },
    { "id": 61, "name": "MASTERY", "description": "to be competent in my everyday activities" },
    { "id": 62, "name": "MINDFULNESS", "description": "to live conscious and mindful of the present moment" },
    { "id": 63, "name": "MODERATION", "description": "to avoid excesses and find a middle ground" },
    { "id": 64, "name": "MONOGAMY", "description": "to have one close, loving relationship" },
    { "id": 65, "name": "MUSIC", "description": "to enjoy or express myself in music" },
    { "id": 66, "name": "NON-CONFORMITY", "description": "to question and challenge authority and norms" },
    { "id": 67, "name": "NOVELTY", "description": "to have a life full of change and variety" },
    { "id": 68, "name": "NURTURANCE", "description": "to encourage and support others" },
    { "id": 69, "name": "OPENNESS", "description": "to be open to new experiences, ideas, and options" },
    { "id": 70, "name": "ORDER", "description": "to have a life that is well-ordered and organized" },
    { "id": 71, "name": "PASSION", "description": "to have deep feelings about ideas, activities, or people" },
    { "id": 72, "name": "PATRIOTISM", "description": "to love, serve, and protect my country" },
    { "id": 73, "name": "PLEASURE", "description": "to feel good" },
    { "id": 74, "name": "POPULARITY", "description": "to be well-liked by many people" },
    { "id": 75, "name": "POWER", "description": "to have control over others" },
    { "id": 76, "name": "PRACTICALITY", "description": "to focus on what is practical, prudent, and sensible" },
    { "id": 77, "name": "PROTECT", "description": "to protect and keep safe those I love" },
    { "id": 78, "name": "PROVIDE", "description": "to provide for and take care of my family" },
    { "id": 79, "name": "PURPOSE", "description": "to have meaning and direction in my life" },
    { "id": 80, "name": "RATIONALITY", "description": "to be guided by reason, logic, and evidence" },
    { "id": 81, "name": "REALISM", "description": "to see and act realistically and practically" },
    { "id": 82, "name": "RESPONSIBILITY", "description": "to make and carry out responsible decisions" },
    { "id": 83, "name": "RISK", "description": "to take risks and chances" },
    { "id": 84, "name": "ROMANCE", "description": "to have intense, exciting love in my life" },
    { "id": 85, "name": "SAFETY", "description": "to be safe and secure" },
    { "id": 86, "name": "SELF-ACCEPTANCE", "description": "to accept myself as I am" },
    { "id": 87, "name": "SELF-CONTROL", "description": "to be disciplined in my own actions" },
    { "id": 88, "name": "SELF-ESTEEM", "description": "to feel good about myself" },
    { "id": 89, "name": "SELF-KNOWLEDGE", "description": "to have a deep and honest understanding of myself" },
    { "id": 90, "name": "SERVICE", "description": "to be helpful and of service to others" },
    { "id": 91, "name": "SEXUALITY", "description": "to have an active and satisfying sex life" },
    { "id": 92, "name": "SIMPLICITY", "description": "to live life simply, with minimal needs" },
    { "id": 93, "name": "SOLITUDE", "description": "to have time and space where I can be apart from others" },
    { "id": 94, "name": "SPIRITUALITY", "description": "to grow and mature spiritually" },
    { "id": 95, "name": "STABILITY", "description": "to have a life that stays fairly consistent" },
    { "id": 96, "name": "TOLERANCE", "description": "to accept and respect those who differ from me" },
    { "id": 97, "name": "TRADITION", "description": "to follow respected patterns of the past" },
    { "id": 98, "name": "VIRTUE", "description": "to live a morally pure and excellent life" },
    { "id": 99, "name": "WEALTH", "description": "to have plenty of money" },
    { "id": 100, "name": "WORLD PEACE", "description": "to work to promote peace in the world" }
]
